#define	HORZ_PIXELS				150
#define	INTENSITY_LEVELS		1
#define	INTENSITY_COUNTER_MAX	1<<(INTENSITY_LEVELS-1)
#define VERTICAL_PIXELS			16
//~ #define VERTICAL_PIXELS			10

#undef PROGMEM_GRAPHIC
#undef DRAW_INIT_HELLO
#undef DRAW_WHEEL_SPEED
