#define	HORZ_PIXELS				200
//~ #define	HORZ_PIXELS				1
#define	INTENSITY_LEVELS		1
#define	INTENSITY_COUNTER_MAX	1<<(INTENSITY_LEVELS-1)
#define VERTICAL_PIXELS			30
//~ #define VERTICAL_PIXELS			10
#define SIDES_COUNT				2
#define SPOKES_COUNT			2
//~ #define VERTICAL_PIXELS			10


#define PROGMEM_GRAPHIC
#undef DRAW_INIT_HELLO
#undef DRAW_WHEEL_SPEED
